# Generated by Django 5.2.8 on 2025-11-14 17:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0002_alter_apartment_options_alter_apartment_id_and_more'),
        ('vendors', '0003_vendor_active_issues_vendor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for security', primary_key=True, serialize=False, unique=True)),
                ('po_number', models.CharField(help_text='Purchase Order Number', max_length=100, unique=True)),
                ('items_count', models.PositiveIntegerField(default=0, help_text='Total number of items in this order')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='draft', max_length=20)),
                ('placed_on', models.DateField(help_text='Date when order was placed')),
                ('expected_delivery', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('actual_delivery', models.DateField(blank=True, help_text='Actual delivery date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Order notes and comments')),
                ('shipping_address', models.TextField(blank=True, help_text='Shipping address if different from apartment')),
                ('tracking_number', models.CharField(blank=True, help_text='Shipping tracking number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apartments.apartment')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-placed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for security', primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(help_text='Name of the product', max_length=255)),
                ('sku', models.CharField(blank=True, help_text='Product SKU', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Product specifications as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['po_number'], name='orders_orde_po_numb_934f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['vendor', 'placed_on'], name='orders_orde_vendor__a4bd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['apartment', 'placed_on'], name='orders_orde_apartme_2660f4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
    ]
