# Generated by Django 5.2.8 on 2025-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='Vendor confirmation reference', max_length=100),
        ),
    ]
