# Generated by Django 5.2.8 on 2025-11-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(max_length=100)),
                ('expected_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Issue Reported', 'Issue Reported')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('proof_photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='apartments.apartment')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='vendors.vendor')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-expected_date'],
            },
        ),
    ]
