# Generated by Django 5.2.8 on 2025-12-07 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_order_delivery_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Issue Reported', 'Issue Reported')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes for this status change')),
                ('changed_by', models.CharField(blank=True, help_text='Who made this change', max_length=255)),
                ('received_by', models.CharField(blank=True, help_text='For Delivered status', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Current location for In Transit', max_length=255)),
                ('delay_reason', models.CharField(blank=True, help_text='Reason for delay', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='deliveries.delivery')),
            ],
            options={
                'verbose_name': 'Delivery Status History',
                'verbose_name_plural': 'Delivery Status Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
