# Generated by Django 6.0 on 2026-01-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_deliverystatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('In Transit', 'In Transit'), ('Delayed', 'Delayed'), ('Received', 'Received'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverystatushistory',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('In Transit', 'In Transit'), ('Delayed', 'Delayed'), ('Received', 'Received'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], max_length=20),
        ),
    ]
