# Generated by Django 5.2.8 on 2025-11-11 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('vendor_link', models.URLField(blank=True)),
                ('sku', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty', models.PositiveIntegerField(default=1)),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Backorder', 'Backorder'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=20)),
                ('status', models.CharField(choices=[('Design Approved', 'Design Approved'), ('Ready To Order', 'Ready To Order'), ('Ordered', 'Ordered'), ('Waiting For Stock', 'Waiting For Stock'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Damaged', 'Damaged'), ('Wrong Item', 'Wrong Item'), ('Missing', 'Missing'), ('Replacement Requested', 'Replacement Requested'), ('Replacement Approved', 'Replacement Approved'), ('Payment Pending', 'Payment Pending'), ('Payment Partial', 'Payment Partial'), ('Payment Complete', 'Payment Complete'), ('Closed', 'Closed')], default='Design Approved', max_length=30)),
                ('eta', models.DateField(blank=True, null=True)),
                ('ordered_on', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='HUF', max_length=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_type', models.CharField(blank=True, max_length=100)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20)),
                ('delivery_country', models.CharField(blank=True, max_length=100)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('delivery_contact_person', models.CharField(blank=True, max_length=255)),
                ('delivery_contact_phone', models.CharField(blank=True, max_length=20)),
                ('delivery_contact_email', models.EmailField(blank=True, max_length=254)),
                ('delivery_time_window', models.CharField(blank=True, max_length=100)),
                ('delivery_notes', models.TextField(blank=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('condition_on_arrival', models.CharField(blank=True, max_length=100)),
                ('issue_state', models.CharField(choices=[('No Issue', 'No Issue'), ('Issue Reported', 'Issue Reported'), ('AI Resolving', 'AI Resolving'), ('Human Action Required', 'Human Action Required'), ('Pending Vendor Response', 'Pending Vendor Response'), ('Resolved', 'Resolved')], default='No Issue', max_length=30)),
                ('issue_type', models.CharField(blank=True, max_length=100)),
                ('issue_description', models.TextField(blank=True)),
                ('replacement_requested', models.BooleanField(default=False)),
                ('replacement_approved', models.BooleanField(default=False)),
                ('replacement_eta', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('manual_notes', models.TextField(blank=True)),
                ('ai_summary_notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='apartments.apartment')),
                ('replacement_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
