# Generated by Django 5.2.8 on 2025-11-11 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Product image URL (up to 500 characters)', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='replacement_of',
            field=models.ForeignKey(blank=True, help_text='Optional: Select the product this item is replacing (leave empty for new products)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='products.product'),
        ),
    ]
