# Generated by Django 5.2.8 on 2025-11-18 17:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_cleanup_migration'),
        ('products', '0003_alter_product_image_url_alter_product_replacement_of'),
        ('vendors', '0003_vendor_active_issues_vendor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Product color', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Product dimensions', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Additional product images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Uploaded product image', null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='import_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw import data for reference'),
        ),
        migrations.AddField(
            model_name='product',
            name='import_row_number',
            field=models.IntegerField(blank=True, help_text='Row number from Excel import', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Product material', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, help_text='Model/Part number', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Thumbnail image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='Product weight', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Product documents and files'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(help_text='Product name/title', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor'),
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('total_sheets', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('successful_imports', models.IntegerField(default=0)),
                ('failed_imports', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='apartments.apartment')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='import_session',
            field=models.ForeignKey(blank=True, help_text='Import session that created this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.importsession'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Category name (from Excel sheet name)', max_length=255)),
                ('import_file_name', models.CharField(blank=True, max_length=255)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('sheet_name', models.CharField(help_text='Original Excel sheet name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('room_type', models.CharField(blank=True, max_length=100)),
                ('priority', models.IntegerField(default=0, help_text='Display order priority')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='apartments.apartment')),
            ],
            options={
                'ordering': ['priority', 'name'],
                'unique_together': {('apartment', 'sheet_name')},
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category from Excel sheet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory'),
        ),
    ]
