# Generated by Django 5.2.8 on 2025-11-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_color_product_description_product_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='all_package',
            field=models.CharField(blank=True, help_text='All Package from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='all_price',
            field=models.CharField(blank=True, help_text='All Price from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.CharField(blank=True, help_text='Cost as text from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, help_text='Product Link from Excel', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='nm',
            field=models.CharField(blank=True, help_text='NM measurement from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='nm_per_package',
            field=models.CharField(blank=True, help_text='NM per Package from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='package_need_to_order',
            field=models.CharField(blank=True, help_text='Package Need to Order from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='plusz_nm',
            field=models.CharField(blank=True, help_text='Plus NM from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_nm',
            field=models.CharField(blank=True, help_text='Price per NM from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_package',
            field=models.CharField(blank=True, help_text='Price per Package from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, help_text='Product Image URL from Excel', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Size from Excel', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sn',
            field=models.CharField(blank=True, help_text='Serial Number from Excel', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.CharField(blank=True, help_text='Total Cost as text from Excel', max_length=100),
        ),
    ]
