# Generated by Django 5.2.8 on 2025-11-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_all_package_product_all_price_product_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Product image URL (up to 2000 characters)', max_length=2000),
        ),
    ]
