# Generated by Django 5.2.8 on 2025-11-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image_url'),
    ]

    operations = [
        # Add delivery_status_tags field
        migrations.AddField(
            model_name='product',
            name='delivery_status_tags',
            field=models.CharField(blank=True, help_text='Comma-separated delivery status tags', max_length=255),
        ),
        # Update delivery_type help text
        migrations.AlterField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(blank=True, help_text='Type of delivery: home_courier, parcel_locker, pickup_point, international, same_day', max_length=100),
        ),
        # Add sender information fields
        migrations.AddField(
            model_name='product',
            name='sender',
            field=models.CharField(blank=True, help_text='Sender name', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='sender_address',
            field=models.TextField(blank=True, help_text='Sender full address'),
        ),
        migrations.AddField(
            model_name='product',
            name='sender_phone',
            field=models.CharField(blank=True, help_text='Sender phone number', max_length=20),
        ),
        # Add recipient information fields
        migrations.AddField(
            model_name='product',
            name='recipient',
            field=models.CharField(blank=True, help_text='Recipient name', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='recipient_address',
            field=models.TextField(blank=True, help_text='Recipient full address'),
        ),
        migrations.AddField(
            model_name='product',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='Recipient phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Recipient email address', max_length=254),
        ),
        # Add parcel locker specific fields
        migrations.AddField(
            model_name='product',
            name='locker_provider',
            field=models.CharField(blank=True, help_text='Locker provider name (e.g., Packeta, GLS ParcelShop)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='locker_id',
            field=models.CharField(blank=True, help_text='Locker ID or code', max_length=100),
        ),
        # Add pickup point specific fields
        migrations.AddField(
            model_name='product',
            name='pickup_provider',
            field=models.CharField(blank=True, help_text='Pickup point provider (e.g., DPD Pickup, GLS Point)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Pickup point location or address', max_length=255),
        ),
        # Add international delivery specific fields
        migrations.AddField(
            model_name='product',
            name='customs_description',
            field=models.TextField(blank=True, help_text='Customs declaration description'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_value',
            field=models.CharField(blank=True, help_text='Declared item value for customs', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_category',
            field=models.CharField(blank=True, help_text='HS (Harmonized System) category code', max_length=100),
        ),
        # Add additional delivery options
        migrations.AddField(
            model_name='product',
            name='insurance',
            field=models.CharField(blank=True, default='no', help_text='Insurance: yes or no', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='cod',
            field=models.CharField(blank=True, help_text='Cash on Delivery amount', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_time',
            field=models.CharField(blank=True, help_text='Pickup time for same-day delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_deadline',
            field=models.CharField(blank=True, help_text='Delivery deadline', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special delivery instructions'),
        ),
    ]
