# Generated by Django 5.2.8 on 2025-11-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_delivery_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_status_tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Product image URL (up to 500 characters)', max_length=500),
        ),
    ]
