# Generated by Django 5.2.8 on 2025-11-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_delivery_status_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_status_tags',
            field=models.CharField(blank=True, help_text='Comma-separated delivery status tags', max_length=255),
        ),
    ]
