# Generated by Django 5.2.8 on 2025-12-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_delivery_status_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='uploaded_file',
            field=models.FileField(
                blank=True,
                help_text='Uploaded Excel/CSV file stored on server',
                null=True,
                upload_to='import_files/%Y/%m/%d/'
            ),
        ),
    ]
