# Generated by Django 6.0 on 2026-01-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_restore_removed_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, help_text='DEPRECATED: Use product_image instead', null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use product_image instead', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, help_text='Primary product image URL (used for all image operations: upload, import, display)', max_length=500),
        ),
    ]
