# Generated by Django 5.2.8 on 2025-11-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('type', models.CharField(choices=[('product', 'Product'), ('payment', 'Payment'), ('delivery', 'Delivery'), ('issue', 'Issue'), ('ai', 'AI'), ('status', 'Status')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='apartments.apartment')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AINote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(choices=[('AI', 'AI'), ('Admin', 'Admin'), ('Vendor', 'Vendor')], max_length=20)),
                ('content', models.TextField()),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('related_to', models.CharField(blank=True, max_length=100)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_notes', to='apartments.apartment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ManualNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_note', to='apartments.apartment')),
            ],
        ),
    ]
