# Generated by Django 5.2.8 on 2025-12-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_add_activity_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Activities'},
        ),
    ]
