# Generated by Django 5.2.8 on 2025-12-09 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_aicommunicationlog_id_alter_issue_id_and_more'),
        ('orders', '0004_orderitem_product'),
        ('products', '0012_alter_delivery_status_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='orders.order'),
        ),
        migrations.AddField(
            model_name='issue',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='issue',
            name='product_name',
            field=models.CharField(blank=True, help_text='Product name for issues without linked product', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='products.product'),
        ),
    ]
