# Generated by Django 5.2.8 on 2025-12-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_order_issue_order_item_issue_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(help_text='Issue type(s), can be comma-separated for multiple types', max_length=500),
        ),
    ]
