# Generated by Django 5.2.8 on 2025-12-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='auto_notify_vendor',
            field=models.BooleanField(default=True, help_text='Automatically notify vendor about this issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected or actual delivery date', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice number for reference', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Notes about the resolution'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_type',
            field=models.CharField(blank=True, help_text='Type of resolution (e.g., Replacement, Refund, Repair)', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Shipping tracking number', max_length=100),
        ),
    ]
