# Generated by Django 5.2.8 on 2025-12-10 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_auto_notify_vendor_issue_delivery_date_and_more'),
        ('orders', '0005_orderitem_product_image_url'),
        ('products', '0012_alter_delivery_status_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for security', primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(blank=True, help_text='Product name for display', max_length=255)),
                ('quantity_affected', models.PositiveIntegerField(default=1, help_text='Quantity of this product affected')),
                ('issue_types', models.CharField(blank=True, help_text='Issue types for this specific product', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Issue description specific to this product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='issues.issue')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_items', to='orders.orderitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_items', to='products.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
