# Generated by Django 6.0 on 2025-12-14 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issueitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicommunicationlog',
            name='ai_confidence',
            field=models.FloatField(blank=True, help_text='AI confidence score (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='ai_model',
            field=models.CharField(blank=True, default='gpt-4', max_length=50),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='email_from',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='email_message_id',
            field=models.CharField(blank=True, help_text='Email Message-ID header', max_length=255),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='email_thread_id',
            field=models.CharField(blank=True, help_text='Email thread identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='email_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='Message was manually edited'),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='message_type',
            field=models.CharField(choices=[('email', 'Email'), ('internal', 'Internal Note'), ('system', 'System Message')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('received', 'Received')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='aicommunicationlog',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='aicommunicationlog',
            name='sender',
            field=models.CharField(choices=[('AI', 'AI'), ('Vendor', 'Vendor'), ('System', 'System'), ('Admin', 'Admin')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='aicommunicationlog',
            index=models.Index(fields=['issue', 'timestamp'], name='issues_aico_issue_i_fdac92_idx'),
        ),
        migrations.AddIndex(
            model_name='aicommunicationlog',
            index=models.Index(fields=['email_thread_id'], name='issues_aico_email_t_ab1b05_idx'),
        ),
        migrations.AddIndex(
            model_name='aicommunicationlog',
            index=models.Index(fields=['status'], name='issues_aico_status_e66380_idx'),
        ),
    ]
