# Generated by Django 6.0 on 2025-12-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_aicommunicationlog_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='first_sent_at',
            field=models.DateTimeField(blank=True, help_text='First email sent to vendor', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='followup_count',
            field=models.IntegerField(default=0, help_text='Number of follow-up emails sent'),
        ),
        migrations.AddField(
            model_name='issue',
            name='last_summary',
            field=models.TextField(blank=True, help_text='AI-generated conversation summary'),
        ),
        migrations.AddField(
            model_name='issue',
            name='last_summary_at',
            field=models.DateTimeField(blank=True, help_text='When summary was last updated', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='next_action',
            field=models.TextField(blank=True, help_text='AI-suggested next action'),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_response_hours',
            field=models.IntegerField(default=24, help_text='Expected response time in hours'),
        ),
        migrations.AddField(
            model_name='issue',
            name='vendor_last_replied_at',
            field=models.DateTimeField(blank=True, help_text='Last time vendor replied', null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolution_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending Vendor Response', 'Pending Vendor Response'), ('Resolution Agreed', 'Resolution Agreed'), ('Closed', 'Closed'), ('Escalated', 'Escalated')], default='Open', max_length=30),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending Vendor Response', 'Pending Vendor Response'), ('Resolution Agreed', 'Resolution Agreed'), ('Closed', 'Closed'), ('Escalated', 'Escalated')], default='Open', max_length=30),
        ),
    ]
