# Generated by Django 6.0 on 2026-01-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_issue_first_sent_at_issue_followup_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicommunicationlog',
            name='html_content',
            field=models.TextField(blank=True, default='', help_text='HTML version of the message for emails'),
        ),
    ]
