# Generated by Django 6.0 on 2026-01-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_aicommunicationlog_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicommunicationlog',
            name='html_content',
            field=models.TextField(blank=True, help_text='HTML version of the message for emails'),
        ),
    ]
