# Generated by Django 6.0 on 2026-01-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_extra_data'),
        ('issues', '0010_alter_aicommunicationlog_html_content'),
        ('orders', '0006_alter_order_status'),
        ('products', '0015_alter_product_image_file_alter_product_image_url_and_more'),
        ('vendors', '0003_vendor_active_issues_vendor_address_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['resolution_status'], name='issues_issu_resolut_ba6f44_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='issues_issu_status_003ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['priority'], name='issues_issu_priorit_77f54b_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['ai_activated'], name='issues_issu_ai_acti_9d07e8_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['vendor'], name='issues_issu_vendor__094f01_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['created_at'], name='issues_issu_created_6f38eb_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['-created_at'], name='issues_issu_created_c92651_idx'),
        ),
    ]
