# Generated by Django 5.2.8 on 2025-11-11 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for security', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name'], name='vendors_ven_name_0d60a8_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['email'], name='vendors_ven_email_3112dd_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['created_at'], name='vendors_ven_created_c4e3ec_idx'),
        ),
    ]
