# Generated by Django 5.2.8 on 2025-11-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_options_alter_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='active_issues',
            field=models.PositiveIntegerField(default=0, help_text='Cached count of active issues for this vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='delivery_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='employee_count',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='lead_time',
            field=models.CharField(blank=True, help_text="Typical delivery lead time, e.g. '7-14 days'", max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.CharField(blank=True, help_text='Optional short logo or emoji', max_length=16),
        ),
        migrations.AddField(
            model_name='vendor',
            name='minimum_order',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='orders_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached total number of orders for this vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='product_categories',
            field=models.TextField(blank=True, help_text='Comma-separated list of product categories'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='reliability',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reliability score from 0.00 to 5.00', max_digits=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='return_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='specializations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='year_established',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
