# Generated by Django 5.2.8 on 2025-11-11 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for security', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for security', primary_key=True, serialize=False, unique=True),
        ),
    ]
