# Generated by Django 5.2.8 on 2025-12-10 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_product_image_url'),
        ('payments', '0003_payment_products'),
        ('products', '0012_alter_delivery_status_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order this payment is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_items',
            field=models.ManyToManyField(blank=True, help_text='Order items included in this payment', related_name='payments', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products included in this payment (legacy)', related_name='payments', to='products.product'),
        ),
    ]
