# Generated by Django 5.2.8 on 2025-11-11 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('furnishing', 'Furnishing'), ('renovating', 'Renovating')], default='furnishing', max_length=20)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Ordering', 'Ordering'), ('Delivery', 'Delivery'), ('Complete', 'Complete'), ('Design Approved', 'Design Approved'), ('Renovating', 'Renovating')], default='Planning', max_length=50)),
                ('designer', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
