# Generated by Django 5.2.8 on 2025-11-11 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
        ('clients', '0002_alter_client_options_alter_client_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Apartment', 'verbose_name_plural': 'Apartments'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for security', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['client'], name='apartments__client__59d349_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['status'], name='apartments__status_e1091c_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['type'], name='apartments__type_f00ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['created_at'], name='apartments__created_f010f7_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['due_date'], name='apartments__due_dat_b2ada5_idx'),
        ),
    ]
