# Generated by Django migration cleanup

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_apartment_options_alter_apartment_id_and_more'),
    ]

    operations = [
        # This migration was created to fix migration dependency issues
        # No actual database changes needed
    ]
