# Generated by Django 5.2.8 on 2025-11-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_cleanup_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional apartment data'),
        ),
    ]
